version: "3"
services:
  nextjs:
    build:
      context: .
      dockerfile: $DOCKERFILE
    ports:
      - 3001:3001
      - 5555:5555
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - ${PROXY_NETWORK_NAME}

  postgres:
    image: postgres:17
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
    networks:
      - ${PROXY_NETWORK_NAME}

networks:
  boilerplate-proxy:
    external: true
